### ISSUE TITLE
Memory Leaking

### ISSUE THREAD

**Issue by doiron99** [Creepsky/creepMiner#233]
CreepMiner seems to have a memory leak problem.  When running in Linux, every day of use adds about 1 gig of memory to total memory use.  Eventually, if left long enough, the machine will completely freeze with hard drives spinning constantly until it's given a hard power off.  The terminal windows don't show a new block on crash.

Closing out CreepMiner does not free the memory.  Only a reboot will free it up again.

I have 10 different machines feeding into on central hub and all of the machines have this problem (including the hub).  It also doesn't matter which version of creep I'm using; I've had this problem since 1.6 and still see it with 1.8.

The number of drives on the machine don't seem to affect the growth rate of memory use; seems fairly consistent at about 1 gig per day if there's 1 or 4 drives on the machines.

I have creep running on a few windows boxes, but they don't stay up long enough to completely crash from it.

**Comment by Beddhist** [comment]
I had a similar problem with 1.7.6. For me it was fixed in 1.7.13. Have you tried that one yet?

**Comment by doiron99** [comment]
I'm running 2.7.13 on about half, the others have been updated to 2.8.  They're still seeing increased memory usage, but it hasn't been long enough for them to full out crash.  I'm keeping tabs on it though.

**Comment by Creepsky** [comment]
What is your `maxBufferSizeMB` setting?

**Comment by doiron99** [comment]
I usually have it set at either 256mb or 512mb.  The memory leak seems to be about half a gig a day at 256, and about a gig a day with 512 so I've been setting it lower to avoid it as much as I can.

**Comment by doiron99** [comment]
I'm 99% sure it's not actually creepminer that's doing the memory leaking.  Seems my remote desktop program (vino) is the source.  Closing thread.
